scanners:
  - type: CSVScanner
    config:
      csv_data: |
        node_name,interface_name,mac_address,ip_address
        node1,lo0,00:11:22:33:44:55,127.0.0.1
managers:
  - type: SequentialManager
    config: {}
    probes:
      - type: PingProbe
        config:
          timeout: 1
          count: 1
reporters:
  - type: CSVReporter
    config:
      output_file: localhost-output.csv
