version: '3'

tasks:
  install:
    desc: Install project dependencies
    cmds:
      - poetry install

  activate:
    desc: Activate the virtual environment
    cmds:
      - poetry shell

  lint:
    desc: Lint the code
    cmds:
      - poetry run flake8 src tests

  format:
    desc: Format the code
    cmds:
      - poetry run black src tests

  test:
    desc: Run tests
    cmds:
      - poetry run pytest

  coverage:
    desc: Generate code coverage report
    cmds:
      - poetry run pytest --cov=src --cov-report=term-missing --cov-report=xml

  run:
    desc: Run the RapidSwarm application
    deps:
      - install
    cmds:
      - poetry run python -m rapidswarm config.yaml

  runlocal:
    desc: Run the RapidSwarm application against localhost
    deps:
      - install
    cmds:
      - poetry run python -m rapidswarm config-localhost.yaml

  clean:
    desc: Clean up generated files and directories
    cmds:
      - rm -rf __pycache__
      - rm -rf htmlcov
      - rm -rf .pytest_cache